// packages/cli/src/cmd/project/templates/services/storage/snippets/sveltekit/page.state.svelte
let exportInfo = $state<{ filename: string; size: number } | null>(null);
let isExporting = $state(false);

async function handleExport() {
	isExporting = true;
	try {
		const res = await fetch('/api/export', { method: 'POST' });
		if (res.ok) exportInfo = await res.json();
	} finally {
		isExporting = false;
	}
}

// packages/cli/src/cmd/project/templates/services/storage/snippets/nuxt/page.state.vue
const exportInfo = ref<{ filename: string; size: number } | null>(null);
const isExporting = ref(false);

async function handleExport() {
	isExporting.value = true;
	try {
		exportInfo.value = await $fetch<{ filename: string; size: number }>('/api/export', {
			method: 'POST',
		});
	} finally {
		isExporting.value = false;
	}
}
