// packages/cli/src/cmd/project/templates/services/keyvalue/snippets/nuxt/page.on-mount.vue
onMounted(async () => {
	try {
		const prefs = await $fetch<{ language?: string; model?: string }>('/api/preferences');
		if (prefs.language && LANGUAGES.includes(prefs.language as (typeof LANGUAGES)[number])) {
			toLanguage.value = prefs.language as (typeof LANGUAGES)[number];
		}
		if (prefs.model && MODELS.includes(prefs.model as (typeof MODELS)[number])) {
			model.value = prefs.model as (typeof MODELS)[number];
		}
	} catch {}
});

// packages/cli/src/cmd/project/templates/services/keyvalue/snippets/sveltekit/page.on-mount.svelte
onMount(async () => {
	try {
		const res = await fetch('/api/preferences');
		if (!res.ok) return;
		const prefs = await res.json();
		if (prefs.language && LANGUAGES.includes(prefs.language)) toLanguage = prefs.language;
		if (prefs.model && MODELS.includes(prefs.model)) model = prefs.model;
	} catch {}
});
