// packages/cli/src/cmd/project/templates/services/queue/snippets/sveltekit/page.state.svelte
interface QueuedJob {
	id: string;
	text: string;
	toLanguage: string;
	model: string;
	at: number;
}
let jobs = $state<QueuedJob[]>([]);

async function handleQueue() {
	const res = await fetch('/api/jobs', {
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		body: JSON.stringify({ text, toLanguage, model }),
	});
	if (!res.ok) return;
	const { id } = (await res.json()) as { id: string };
	jobs = [{ id, text, toLanguage, model, at: Date.now() }, ...jobs];
}

// packages/cli/src/cmd/project/templates/services/queue/snippets/nuxt/page.state.vue
interface QueuedJob {
	id: string;
	text: string;
	toLanguage: string;
	model: string;
	at: number;
}
const jobs = ref<QueuedJob[]>([]);

async function handleQueue() {
	const res = await $fetch<{ id: string }>('/api/jobs', {
		method: 'POST',
		body: { text: text.value, toLanguage: toLanguage.value, model: model.value },
	});
	jobs.value = [
		{
			id: res.id,
			text: text.value,
			toLanguage: toLanguage.value,
			model: model.value,
			at: Date.now(),
		},
		...jobs.value,
	];
}
